### PR TITLE
ctest: add basic functional tests

### PR DESCRIPTION
**Pull request by ldorau**

### CODE REVIEW

**Comment by vitalyvch** [comment]
Is it correct that tests traces the same exe with strace and strace.ebpf and then unify and compare output.

**Comment by ldorau** [comment]
> Is it correct that tests traces the same exe with strace and strace.ebpf and then unify and compare output.

It is just one of possible ways of functional testing of strace.ebpf. System 'strace' is used as a reference point only in some of my tests, even these less important ones. 

What doubts do you have about it?

**Comment by vitalyvch** [comment]
So, I believe you should describe it in comments in few sentences. It will be enough for me.

**Comment by ldorau** [comment]
OK, I will do that

**Pull request merged**
